### ISSUE TITLE
InputDatePicker not showing date carousel on iOS RN 0.28

### ISSUE THREAD

**Issue by jamieathans** [bmcmahen/panza#19]
Can verify this was working on RN 0.27.2

![simulator screen shot 24 jun 2016 5 40 11 pm](https://cloud.githubusercontent.com/assets/16371427/16332087/3fed6a40-3a33-11e6-8e9d-e12601a34f8c.png)

**Comment by bmcmahen** [comment]
Unfortunately there is significant breakage with 0.28 -- enough that I think I'll wrap 0.28 support into the version 3 release. I would accept a PR, though, for 0.28 with the current v2 release.

**Comment by bmcmahen** [comment]
This has been fixed on master.
