### ISSUE TITLE
Allow customization of config without root context

### ISSUE THREAD

**Issue by hammadj** [bmcmahen/panza#21]
supplying a context from the app root isn't always an option in react native (i.e. when using multiple roots) and the current way of setting up the custom config options is pretty messy (relies on user remembering to Object.assign to default config).

I propose we have something like this where the user can call once anywhere in their application:

```
import panza from 'panza'

panza.configure({
  colors: {
    primary: '#505050',
    customColor: '#123456'
  }
})
```

Also, I think we should change how the size configs work. Instead of arrays, we should have objects with keys:
```
const fontSizes = {
  1: 48,
  2: 32,
  3: 24,
  4: 20,
  5: 17,
  6: 15,
  7: 12
}
```

This way users will be able to customize the font/line-height/scale configurations easier

Let me know what you think and I can put something together sometime soon.

**Comment by bmcmahen** [comment]
Yeah, I like this. Setting it via context is a holdover from `rebass`. One of the advantages of using context is that it is reactive -- i.e., you could change your theme on the fly, and all of your components would be re-rendered immediately. How useful this is in practice is questionable, though. I would ultimately favour a better api even if it limits this possibility, somewhat. 

Having fontSizes as an object makes a lot of sense. Definitely down with that. 

Another concern of mine currently is with performance. I haven't really encountered any performance issues so far, but I imagine that converting props to styles as done in the Base component has some negative performance implications. Perhaps this could be remedied using `PureRenderMixin`, or some other means. Again, though, I think this is a low priority until performance becomes an obvious problem.

**Comment by hammadj** [comment]
Yea the use case for needing reactive themes is pretty niche, and if someone was going to do that for their app they would probably roll their own solution.

Another thing I would like to do is refactor the Text components (PrimaryText, SecondaryText, etc) into one Text component and specify the type in the props:  `<Text primary color={'red'} />`. And similarly for button components:
```
<Button error />
<Button success />
<Button rounded basic success icon="icon-name" />
```

P.S. created a new issue for discussion on performance #22

**Comment by bmcmahen** [comment]
I'm not totally convinced that `<Button primary />` is better than `<PrimaryButton />`, in part because I think it makes the `<Button />` render logic more complex. In some ways, I feel like the composition that is currently being used is cleaner and more elegant. Do you just prefer the `<Button primary />` syntax? If we eventually do build a more complex `Button` that handles all of these props, it should still compose a `BaseButton` and other components -- i.e., something similar to what is currently done with TouchableRow. But in general, I prefer having multiple components with simple render functions over those with complex ones.

**Comment by hammadj** [comment]
My main motivation for having props over composition is being able to have less components to maintain, less boilerplate overall for the user since they have less components exposed to them, and a cleaner more semantic syntax that could be arbitrarily composed. ie:
```
<Button rounded basic success />
<Button large error  />
```
It would make the API more consistent since we are already doing things like 'block' and 'disabled'. The rendering logic can be made fairly straightforward too, we could just have an object that stores the corresponding props for each boolean prop with the name of the boolean as the key and concatenate them all into one set of props using a common function and pass them down to a BaseButton component. something like this:

```
const mapBooleanProps(props, propsMap) {
	return Object.assign(..._.filter(propsMap, (v, k) => props[k]), props)
}

const buttonPropsMap = {
	rounded: { rounded: 4 }
	large: { p: 3 },
	error: { backgroundColor: 'error', textColor: 'white', borderColor: 'error' }
    primary: { backgroundColor: 'primary', textColor: 'white', borderColor: 'primary' }
	basic: { backgroundColor: 'transparent', borderWidth: 2 }
	

	//...
}

const Button = (props) => <BaseButton {...mapBooleanProps(props, buttonPropsMap)} />	
```
With this, the user could type this:
```
<Button basic large error textColor="green" />
```
and it would render this:
```
<BaseButton 
  backgroundColor="transparent" 
  borderWidth={2}
  borderColor="error"
  textColor="green"
  p={3}
/>
```

It would really clean up the code base, we don't have too many components yet and its already looking really busy. This way we can have "smart" base components hidden from the user that contain all the logic and a few wrapper components with the syntactic sugar. Code would be a lot easier to maintain and iterate to add new features on if we only have to modify base classes or add new properties to any  'propMaps' we may have

**Comment by bmcmahen** [comment]
I think you've convinced me, as long as we maintain the flexibility that composition typically provides. Way too often I've started developing something with a ui library, and ended up ditching it because it didn't provide the flexibility that I wanted -- both in terms of its appearance, and in terms of the functionality.

Which are the unique props for Button, then?

`rounded`, `textColor`, `backgroundColor`, `large`, `small`
 and `primary`, `warning`, `success`, `error`
`disabled`, `block`

Ideally, border would be a universal prop provided in `Base`. 

I still want to be able to provide custom children to the Button, including things like Icons, custom text, and basically anything else we want.

**Comment by hammadj** [comment]
I think `rounded`, `large`, `small`, `circular`, `primary`, `secondary`, `positive`, `negative`, `disabled`, `block`, `basic` and `icon`  would be a good set of props for Button. 

I would like to change `success` and `error` to `positive` and `negative` since it makes more sense for buttons. i.e. calling a red delete button an "error" button seems wrong. 

Also, I think having to manually nest an icon in a button and positioning and styling it yourself isnt ideal, so we could use the icon prop as a string (while the rest of them are bools) and have standard behavior for how it appears in a button. Of course users could still nest it themselves if they wish.

The basic prop would just make the button outlined instead of filled, something like this:
![image](https://cloud.githubusercontent.com/assets/7143583/16404325/22e18b22-3cbb-11e6-9c46-c0c186aac00b.png)

Also, I think we should define a better set of default colors: `default` (if no color is passed in), `primary`, `secondary`, `positive`, `negative`, `red`, `orange`, `yellow`, `green`, `blue`, `purple`, `pink`, `brown`, `grey`, `black`, `white`

**Comment by bmcmahen** [comment]
Sounds good, except I think we need something more descriptive than `basic` to indicate an outline. I'd prefer something like `outline`.

**Comment by hammadj** [comment]
Yea `outlined` would be better, and we can also add `transparent` as a replacement for the naked button.
