### ISSUE TITLE
Performance discussion

### ISSUE THREAD

**Issue by hammadj** [bmcmahen/panza#22]
I was testing performance with react-perf-tools yesterday and if I hadn't already optimized the container components with shouldComponentUpdate and immutable data, the Base > View took up the majority of wasted render time (calculated using Perf.printWasted()). This becomes a significant problem especially when you use the Base component everywhere as a replacement for View because of the nice syntax. 

Here are the options we have that I could think of right off the bat:
- shouldComponentUpdate
- memoize calculation functions in Base (margins, paddings, colorStyle, radii, underlay). lodash memoize should work like a charm
- create a separate component that is more stripped down and light-weight as a replacement for View instead of having to use Base, but would still support the nice layout syntax (mt, p, flex, etc)

shouldComponentUpdate might help the situation, but could also make it even slower since it's an extra function that needs to be called on every base component. Will have to do some more testing to verify if it would help, but even if it would we shouldn't resort to using it if we don't have to. The library should be as performant as possible and we should leave the advanced tuning with things like shouldComponentUpdate to the user.

I think if the memoization works well the second point woudn't even be necessary. I'll try doing some benchmarking and see what combination of the options above works best

**Comment by bmcmahen** [comment]
Great stuff. Thanks for looking into this. Agreed that memoization is a good start. Another more complex possibility would involve some form of static transform -- ideally something to be avoided, I think, but I believe that React Native inlines things like `Platform.select` during the build process for perf reasons. 

Also, my sense is that the performance of the functions in Base could be improved fairly easily. A lot of it was done in haste.

**Comment by hammadj** [comment]
Okay so I did some benchmarking comparing Base to View. For the test I rendered 200 views with a random number from 1-100 and the background color set between red and green depending on the number. Running the benchmark updates 50 of the views with a new number and color every 0.1 seconds for 2 seconds. Here were the results for various test cases:

| Component                          |  Avg Time of 10 Runs (ms) | 
|------------------------------------|---------------------------| 
| View                               | 706.2                     | 
| Base (no props)                    | 1590                      | 
| Base (bgColor + padding + margin)  | 1707                      | 
| Base (all props)                   | 1887.8                    | 
| Base (SCU)                         | 405.6                     | 
| View (with Child)                  | 887.6                     | 
| Base (with Child)                  | 1899.4                    | 
| Base (with Child + SCU)            | 1912.6                    | 

Relatively, the Base component takes twice as long to render as the view component, however, the absolute performance cost is pretty much negligible once you factor in all the other components that would exist in a real app. ShouldComponentUpdate really speeds things up as long as Base doesn't have a child that is updated, which is almost never so it doesn't make sense to put it in, the user should manage this themselves. I tried playing with memoization but any performance gains were negligible and it would add a layer of complexity/break some tests. Overall, I don't think we need to worry about this at all unless we see some performance problems in a real production app due to this.

**Comment by bmcmahen** [comment]
Awesome stuff man. Thanks a bunch! Nice to know that performance shouldn't really be a priority at this stage. We should probably ensure that we document ShouldComponentUpdate, though, to ensure that users are at least aware of it.

**Comment by hammadj** [comment]
Closing this for now since performance isnt really an issue
