### ISSUE TITLE
Fix Documentation Generation

### ISSUE THREAD

**Issue by hammadj** [bmcmahen/panza#24]
trying to run generate-docs script right now gives errors because of multiple exports in some components (Icon) and also because its trying to read the index.js files. Not too familiar with how react-docgen is setup and works.

generate-doc-json:
```
Error with path "components/panza/RowInput/RemovableInput.js": Error: Multiple exported component definitions found.
Error with path "components/panza/Text/index.js": Error: No suitable component definition found.
```
generate-doc-markdown: 
```
Error: ENOENT: no such file or directory, open '/Users/hammadjutt/Dev/panza/scripts/../documentation/components/panza/RowInput/RevealingRow.js.md'
```

**Comment by bmcmahen** [comment]
I'll look into it. react-docgen was acting kinda weird for me before, too. I'd like to nail this down, and clean up the docs before the next major release, and also ensure that all of propTypes are correct.

**Comment by hammadj** [comment]
Also, as a part of the "fancy website", we could use gitbooks.com for the docs.

**Comment by bmcmahen** [comment]
Cool. I'll look into it. Another thought is to use react-native-web to render the ui-components. That would be kinda sexy.

**Comment by hammadj** [comment]
Yea that would be really cool! Ideally I would still like to be able to use something like gitbooks so we can automatically update docs and keep them in sync everywhere. I wonder if we could embed react native web views into gitbooks...

We can also use github pages to have a home page and then link to the gitbook docs from there.

**Comment by bmcmahen** [comment]
I'll probably have some time this weekend to hack away on this project. I'll try to sort out the documentation, create a new org, and figure out the basic skeleton of the project.

**Comment by bmcmahen** [comment]
Ugh, from what I gather, react-docgen does not support multiple named exports in the same file. I guess, for now, I'll attempt to split up all the named exports into different files.

**Comment by hammadj** [comment]
Just saw all the new stuff, great job man! I've been busy for the past few weeks (and will be for another 2 weeks) with a product launch so I haven't been able to work on this stuff, but right after that I'll be back in business.

Gitbook is basically like a CMS, it can read from and write to the repository automatically, so you can go to the gitbook site and edit things there and the changes will be reflected in the repo here. It's basically a static site generator without the setup, it's what redux uses (http://redux.js.org/)

**Comment by bmcmahen** [comment]
Awesome -- I have a small project that I want to use this for, so I'll probably start using the outline of this new version in the coming weeks. But I'll wait to publish v3 until I get your feedback & maybe some code review. I'm also hoping to sort out react-native-web support, although setup (managing babel, dependencies, & a separate build) is a pain in the butt.

**Comment by hammadj** [comment]
Great, yea ill have a look at everything next week sometime, review the code as well

**Comment by bmcmahen** [comment]
Gitbooks is working on the `docs` branch. Running `npm run docs:publish` reads the propTypes from our various components, generates the respective markdown files, runs gitbooks with a series of plugins, and pushes it to the gh-pages branch. The docs still need a lot of work, but the basic framework is there, now.

**Comment by bmcmahen** [comment]
Documentation is online here: http://bmcmahen.github.io/panza/

**Comment by hammadj** [comment]
Sorry for the delay, I'm finally going through all the new stuff and documentation today. Could you invite me to the gitbooks so I can play around in there? Have a few ideas for consolidating our documentation with the examples and UI Explorer.

**Comment by bmcmahen** [comment]
sent you an invite, although i'm not really using gitbooks the website at all. I am using their open source lib, and publishing it on the gh-pages branch, though. You can mess around with the documentation by looking at the npm scripts -- including npm run docs:watch -- to get a sense of how the process works now. The examples are now working with react-native-web, although it's definitely quite hacky at this stage. 

Also, make sure you check out the 'docs' branch. I've been working on v3 there for the last couple of weeks.

**Comment by hammadj** [comment]
ah ok, that makes sense now, didnt know you were working on the docs branch. I was confused because the content on gitbooks site didnt match the repo. Thanks, will start digging through the docs repo!

**Comment by hammadj** [comment]
I made a slack for us so we can chat and bounce back ideas instead of having to comment on this each time for small things. Got a few questions about the new structure
