### ISSUE TITLE
I guess this project is dead

### ISSUE THREAD

**Issue by ruskid** [bmcmahen/panza#38]
master has bugs

v3 is completely different from v2, rewriting config by context doesn't work on v3. Only temp fix is using panza prop. 

Examples folder contains examples for v3 and master, when readme covers v2.

InputToggle's onTintColor doesn't work. And a lot more small details I didn't cover.

It's a pity, cause I really like the idea of customizable stateless components.

**Comment by bmcmahen** [comment]
It's not dead, i just haven't committed any of the local changes that I've made to open source. In effect, it's the library I use to build my react-native apps, and it evolves as I build more apps. The goal is to get v3 into a workable, stable state within the next few weeks. You can follow the progress on the `docs` branch.

v3 config no longer uses context, but now exposes a `customizeTheme` function and uses higher order components instead. The benefits of using context were minimal, and therefore ditched.

**Comment by ruskid** [comment]
Ok I didn't notice customizeTheme function. I will take a look then, thanks!
