### ISSUE TITLE
Button doesnt have underlay color when setting custom backgroundColor

### ISSUE THREAD

**Issue by hammadj** [bmcmahen/panza#7]
When setting the backgroundColor prop on the Button component, the button doesnt darken like it does when using a preset color.

with ` <Button backgroundColor='midgray'/>`  (second button is pressed):
![img_2115](https://cloud.githubusercontent.com/assets/7143583/15997319/c8142c76-30ef-11e6-9a99-ae691ea43e0e.jpg)

with ` <Button backgroundColor='#e6e6e6'/>`  (second button is pressed) :
![img_2114](https://cloud.githubusercontent.com/assets/7143583/15997321/ca669b4e-30ef-11e6-8ab3-dc596ea828e3.jpg)

I believe it has to do with these lines: https://github.com/bmcmahen/panza/blob/master/components/panza/Base/Base.js#L131-L137

**Comment by bmcmahen** [comment]
Good catch. This should be an easy fix. I'll look into it tomorrow.

**Comment by hammadj** [comment]
Just tried out the latest commit, it seemed to have broken something in the Base component because having a panza component anywhere causes these errors:

```
Warning: Failed propType: Invalid props.style key `color` supplied to `View`.
Bad object: {
  "paddingLeft": 16,
  "paddingRight": 16
}
Valid keys: [
  "width",
  "height",
  ...
] Check the render method of `Base`.
```
```
Warning: Failed propType: Invalid props.style key `color` supplied to `RCTView`.
Bad object: {
  "paddingLeft": 16,
  "paddingRight": 16
}
Valid keys: [
  "width",
  "height",
  ...
] Check the render method of `View`.
```

PS. Excellent work so far on this library! RN really needs something like what the web has with Bootstrap, this seems like an awesome solution.

**Comment by bmcmahen** [comment]
Can you try against the latest master again? I've made a few changes to the colour functions which may have been broken and are (hopefully) now fixed. Oh, and glad you're finding the library useful! Thanks for helping me find some of these bugs.

**Comment by hammadj** [comment]
Yup, latest version seems to be working beautifully! Thanks! I'm going to be using this in my app so as I get more familiar with and and get ideas for improvements I'll make some pull requests :)

**Comment by bmcmahen** [comment]
Awesome! Feedback and PRs would be great. I'm open to any suggestions -- in particular, with respect to the scope of this project (which components we should include), and with the behaviour of the Base function (which props are transformed into styles, & how the global config overrides some of these styles).
